### ISSUE TITLE
Add a URI scheme deep link

### ISSUE THREAD

**Issue by th0rgall** [iIDRAGONFIREIi/minimalistic_push#1]
Hi! I'm working for [Potential](https://potential.app/), a habit-tracking app that lets people set intentions and launch other apps to complete those intentions.

One of our users loves Minimalistic Push and would like to launch it from Potential. We usually do this with the URI scheme of an app.

Unfortunately Minimal Push does not have a URI scheme set yet. It should be simple to add. Following [these Flutter docs](https://docs.flutter.dev/development/ui/navigation/deep-linking#enable-deep-linking-on-ios), I produced a commit with the changes that should add a deep link: https://github.com/th0rgall/minimalistic_push/commit/c1ce17ce1c0a516743c33299bbb8cde6b161a410.

I did not make suggest a PR yet because it seems the code here is relatively old now, and there is at least one compilation issue:

```bash
thor@pc minimalistic_push % flutter pub get
Running "flutter pub get" in minimalistic_push...                  13.9s
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `gallery_saver` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
```
It seems someone has to go through this [migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) first. @jonaspoxleitner are you intending to keep maintaining this project?

**Comment by jonaspoxleitner** [comment]
Update will roll out soon!

**Comment by th0rgall** [comment]
Late reaction, but thanks a lot Jonas!
